create table public.notes (
    id bigint generated by default as identity,
    title text not null,
    content text not null,
    created_date date null,
    constraint notes_pkey primary key (id)
);
create table public.users (
    id uuid not null default gen_random_uuid (),
    name text not null,
    email text not null,
    constraint users_pkey primary key (id),
    constraint users_email_id_key unique (email)
);
create table public.user_notes (
    note_id integer not null,
    user_id uuid not null,
    
    constraint user_notes_pkey primary key (user_id, note_id),
    constraint user_notes_note_id_fkey foreign key (note_id) references notes (id),
    constraint user_notes_user_id_fkey foreign key (user_id) references users (id)
);